import Header from "components/Header"
import Navbar from "components/Navbar"
import Results from "components/Results"
import Head from "next/head"
import requests from "utils/requests"



export default function Home({results}) {
  console.log(results);
  return (
    <>
      <Head>
        <title>Zulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
            {/* Header */}
            <Header/>

            {/* Navbar */}
            <Navbar/>
            {/* Results */}
            <Results results= {results}/>
      </div>
     

       
  
  


       

        
    </>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";
  const request = await fetch(`
  https://api.themoviedb.org/3/${requests[genre].url}
  `).then((response) => response.json());
  

  return {
    props: {
      results: request.results,
    },
  };
}


